### ISSUE TITLE
When client sends update for its registration info it stops handleing incoming requests

### ISSUE THREAD

**Issue by kudla** [telefonicaid/lwm2m-node-lib#39] opened 2015-04-01 10:52 UTC
When client sends update for its registration info it stops handleing incoming requests.

I don't know where the chain bearks but event [dataHandler](https://github.com/telefonicaid/lwm2m-node-lib/blob/develop/lib/services/coapRouter.js#L41) don't treat this.

**Comment by dmoranj** [comment] 2015-04-01 11:00
I'll try to reproduce, maybe the change in port is not correctly handled (it should stop the listener in the older port and start it in the new one).

**Comment by dmoranj** [comment] 2015-04-01 11:01
This is pending of a important change in the library (to use the same socket for listening and sending).

**Comment by dmoranj** [comment] 2015-04-28 13:34
Can't reproduce. I tried with the server and client comand line tools, updating several times the connections, and performing reads and writes in between, and it seemed to work without problems. Can you specify what operations were you performing when you detected the error?

**Comment by dmoranj** [comment] 2015-04-29 14:55
Closed as it was not reproducible. Will be reopend in case a proper test case is provided.

**Closed** 2015-04-29 14:55 UTC
Labels: bug
